// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuqSnVcUSyx8pRjpt88Nfe6c2CHzb8dU8',
    appId: '1:377914246325:web:d873ce01fad13398012afc',
    messagingSenderId: '377914246325',
    projectId: 'down2hang',
    authDomain: 'down2hang.firebaseapp.com',
    storageBucket: 'down2hang.appspot.com',
    measurementId: 'G-732R4HYFMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwQ6ZkKK-O-sFUKhenFB_Navb3xTr6RHI',
    appId: '1:377914246325:android:e71d0de2747bfe08012afc',
    messagingSenderId: '377914246325',
    projectId: 'down2hang',
    storageBucket: 'down2hang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALhZmSMQGz1QhZp2bpSwvGVc6HlG3YLRo',
    appId: '1:377914246325:ios:e774bb8e0147de4b012afc',
    messagingSenderId: '377914246325',
    projectId: 'down2hang',
    storageBucket: 'down2hang.appspot.com',
    iosClientId: '377914246325-44nnpr0sktvs87np5oq8bled9m1g4fut.apps.googleusercontent.com',
    iosBundleId: 'com.example.downTwoHang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALhZmSMQGz1QhZp2bpSwvGVc6HlG3YLRo',
    appId: '1:377914246325:ios:e774bb8e0147de4b012afc',
    messagingSenderId: '377914246325',
    projectId: 'down2hang',
    storageBucket: 'down2hang.appspot.com',
    iosClientId: '377914246325-44nnpr0sktvs87np5oq8bled9m1g4fut.apps.googleusercontent.com',
    iosBundleId: 'com.example.downTwoHang',
  );
}
